/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volumecalculator;

import java.text.DecimalFormat;

/**
 *
 * @author 100697281
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pipsField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        riskBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        feedbackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VantageFX Volume Calculator");
        getContentPane().setLayout(null);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("FX Volume Calculator");
        titleLabel.setToolTipText("");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(0, 0, 400, 80);

        balanceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        balanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(balanceField);
        balanceField.setBounds(230, 80, 80, 20);

        jLabel1.setText("Base Balance:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 80, 84, 20);

        jLabel2.setText("Pips to S/L:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 80, 20);

        pipsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pipsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pipsField);
        pipsField.setBounds(230, 150, 80, 20);

        jLabel4.setText("Risk %:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 120, 80, 20);

        riskBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "5", "50", "100" }));
        riskBox.setSelectedIndex(1);
        riskBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskBoxActionPerformed(evt);
            }
        });
        getContentPane().add(riskBox);
        riskBox.setBounds(260, 120, 45, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Volume:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 240, 80, 20);

        outputLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        outputLabel.setMaximumSize(new java.awt.Dimension(41, 16));
        outputLabel.setMinimumSize(new java.awt.Dimension(41, 16));
        getContentPane().add(outputLabel);
        outputLabel.setBounds(240, 240, 50, 20);

        calculateButton.setText("CALCULATE");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateButton);
        calculateButton.setBounds(140, 190, 120, 32);

        feedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        feedbackLabel.setText("press \"CALCULATE\" when each entry has been filled");
        getContentPane().add(feedbackLabel);
        feedbackLabel.setBounds(0, 270, 400, 40);

        setSize(new java.awt.Dimension(416, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
void update() {
        //initialize
        String feedback = "";
        double volume;
        // get each value
        boolean validBalance, validpips;
        //balanceField
        String bal = balanceField.getText();
        double balance = 0;
        //parse to double
        try {
            balance = Double.parseDouble(bal);
            validBalance = true;
        } catch (NumberFormatException e) {
            validBalance = false;
        }
        //riskBox
        double risk;
        switch (riskBox.getSelectedIndex()) {
            case 0:
                //1
                risk = 0.01 * balance;
                break;
            case 1:
                //2
                risk = 0.02 * balance;
                break;
            case 2:
                //5
                risk = 0.05 * balance;
                break;
            case 3:
                //50
                risk = 0.5 * balance;
                break;
            default:
                //100
                risk = 1 * balance;
                break;
        }
        //pipsField
        String pip = pipsField.getText();
        double pips = 0;
        //parse to double
        try {
            pips = Double.parseDouble(pip);
            validpips = true;
        } catch (NumberFormatException e) {
            validpips = false;
        }
        //calculation
        if (validpips && validBalance) {
            volume = risk / pips;
            //output to outputLabel and feedback
            //valid
            DecimalFormat f = new DecimalFormat("0.0#");
            outputLabel.setText(f.format(volume));
            feedbackLabel.setText("");
        } else {
            feedback = "Please enter real numbers into the \"Pips\" and \"Balance\" Fields";
            //output to outputLabel and feedback
            //invalid
            outputLabel.setText("0.00");
            feedbackLabel.setText(feedback);
        }

    }
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        update();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void riskBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskBoxActionPerformed
        update();
    }//GEN-LAST:event_riskBoxActionPerformed

    private void balanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceFieldActionPerformed
        update();
    }//GEN-LAST:event_balanceFieldActionPerformed

    private void pipsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipsFieldActionPerformed
        update();
    }//GEN-LAST:event_pipsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceField;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextField pipsField;
    private javax.swing.JComboBox<String> riskBox;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
